export DENO_INSTALL="/home/devanandpa/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
#export "$(dbus-launch)"
export PATH="$PATH:$HOME/.local/bin:$HOME/.scripts/bin:$HOME/sourced/android-studio/bin:$HOME/sourced/build_linux/bin:$HOME/sourced/blender-4.1.1-linux-x64"
. "$HOME/.cargo/env"
[ -d "/usr/local/gromacs/bin" ] && PATH="$PATH:/usr/local/gromacs/bin"
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
