#!/bin/env python3
import shutil
import os
from contextlib import suppress
import sys
import subprocess
import json

args = sys.argv[1:]


def select_Trash() :
    Tlist=""
    for i in os.listdir(os.path.expanduser('~/Trash/')):
        Tlist += i+"\n"
    trash_data = os.path.expanduser("~/.trash_files/trash_data")
    with open(trash_data)  as FILE :
        DATA = list(FILE.read().split('\n'))
    datas = []
    DATA2 = []
    
    if os.listdir(os.path.expanduser('~/Trash/')):
        sel = subprocess.check_output(["fzf","-m"],input=bytes(Tlist,"utf-8"))
        sel = sel.decode("utf-8")
        sel = list(sel.split('\n'))
        sel.pop(-1)
        if not sel  :
            quit()
        unsel = []
        for i in range(len(DATA)):
            if DATA[i] != "" :
                data = json.loads(DATA[i])
                DATA2.append(data)
            for j in range(len(sel)) :
                if data["TrashName"] == sel[j] :
                    datas.append(data)
                    while data in DATA2 :
                        DATA2.remove(data)
    
        for i in range(len(datas)) :
            j = datas[i]["OrigName"]
            test = j
            k = 0 
            while os.path.exists(test) :
                test = test+"_"+str(k)
                k = k +1
            datas[i]["OrigName"] = test
            unsel.append(datas[i])
    
        with open(trash_data,"w")  as FILE :
            FILE.write("")
        
        if DATA2 :
            with open(trash_data,"a") as FILE :
                for i in DATA2:
                    FILE.write(json.dumps(i))
                    FILE.write("\n")
    
        for i in range(len(unsel)) :
            Trash_Path = os.path.expanduser("~/Trash/"+unsel[i]["TrashName"])
            if os.path.isdir(Trash_Path) :
                shutil.rmtree(Trash_Path)
            elif os.path.isfile(Trash_Path) :
                os.remove(Trash_Path)
    
    else :
        print("No Trash to remove")

def main() :
    trash_data = os.path.expanduser("~/.trash_files/trash_data")
    if "-a" in args :
        shutil.rmtree(os.path.expanduser('~/Trash'))
        with open(trash_data,'w')  as FILE :
            FILE.write('')
        os.mkdir(os.path.expanduser('~/Trash'))
    else :
        select_Trash()

if __name__ == "__main__" :
    main()
