#!/bin/python3
import os
import subprocess
import sys

ARGS=sys.argv
musicdir=os.path.expanduser("~/Music/") # ~/Music/

# Select What to do
mode = subprocess.check_output(["dmenu","-l","30","-i"],input="Play Playlist\nPlay Song\nCreate Playlist",text=True).rstrip() 

# Create Playlist
if (mode=="Create Playlist") :
    ## Remove txt and vtt files from find
    all_songs=subprocess.check_output(["find",musicdir],text=True).rstrip().split('\n')
    for song in all_songs :
        if song[-3:] in ["vtt","txt"] :
            all_songs.remove(song)
    all_songs="\n".join(all_songs).rstrip()
    ## select songs from find
    selected_songs=subprocess.check_output(["dmenu","-p","Select Songs","-l","30","-i"],text=True,input=all_songs).rstrip()
    

    ## Name Playlist
    playlist_name = subprocess.check_output(["dmenu","-p","Name the Playlist","-i"],text=True,input="").rstrip()
    with open(musicdir+"Playlists/"+playlist_name+".txt",'w') as playlist_file :
        playlist_file.write(selected_songs)


# Play Playlist
elif (mode=="Play Playlist") :
    all_playlists=subprocess.check_output(["ls",musicdir+"Playlists/"],text=True).rstrip()
    selected_playlist=subprocess.check_output(["dmenu","-p","Select a playlist","-l","30","-i"],text=True,input=all_playlists).rstrip()
    selected_playlist=musicdir+"Playlists/"+selected_playlist
    print(selected_playlist)
    subprocess.run(['mpv','ao=alsa','--player-operation-mode=pseudo-gui','-fs','--sub-pos=55','--sub-scale=0.75','--no-resume-playback',"--playlist="+selected_playlist,'shuffle=yes']+ARGS)

elif (mode=="Play Song"):

    ## Remove txt and vtt files from find
    all_songs=subprocess.check_output(["find",musicdir],text=True).rstrip().split('\n')
    for song in all_songs:
        if song[-3:] in ["vtt","txt"] :
            all_songs.remove(song)
    all_songs="\n".join(all_songs).rstrip()
    ## select songs from find
    selected_songs=subprocess.check_output(["dmenu","-p","Select Songs","-l","30","-i"],text=True,input=all_songs).rstrip()
    selected_songs = selected_songs.split('\n')
    subprocess.run(['mpv','ao=alsa','--player-operation-mode=pseudo-gui','-fs','--sub-pos=55','--sub-scale=0.75','--no-resume-playback']+selected_songs+['shuffle=yes']+ARGS)

