#!/bin/python3
import os
import subprocess
import sys
import tempfile

ARGS=sys.argv
musicdir=os.path.expanduser("~/Music/") # ~/Music/
menu = ["dmenu","-i","-l","35"]
# Select What to do
mode = subprocess.check_output(menu+["-p","What do you want to Do ?"],input="Play Playlist\nPlay Song\nCreate Playlist\nAdd to Playlist\nRemove from Playlist",text=True).rstrip() 

if (mode == "Remove from Playlist") :
    all_playlists=subprocess.check_output(["ls",musicdir+"Playlists/"],text=True).rstrip()
    selected_playlist=subprocess.check_output(menu+["-p","Select a playlist"],text=True,input=all_playlists).rstrip()
    selected_playlist=musicdir+"Playlists/"+selected_playlist
    with open(selected_playlist) as FILE :
        songs_in_playlist = FILE.read()
    selected_songs=subprocess.check_output(menu+["-p","Select Songs to remove"],text=True,input=songs_in_playlist).rstrip()
    songs_in_playlist = list(songs_in_playlist.split('\n'))
    selected_songs = list(selected_songs.split('\n'))
    for i in range(len(songs_in_playlist)-1,-1,-1) :
        for song in selected_songs :
            if songs_in_playlist[i] == song :
                del songs_in_playlist[i]
                print("removed",song)
                break

    all_songs="\n".join(songs_in_playlist).rstrip()
    with open(selected_playlist,'w') as FILE :
        FILE.write(all_songs)



## Add to playlist
if (mode=="Add to Playlist") :
    all_playlists=subprocess.check_output(["ls",musicdir+"Playlists/"],text=True).rstrip()
    selected_playlist=subprocess.check_output(menu+["-p","Select a playlist"],text=True,input=all_playlists).rstrip()
    selected_playlist=musicdir+"Playlists/"+selected_playlist
    with open(selected_playlist) as FILE :
        songs_in_playlist = [ i.rstrip() for i in FILE.readlines()]

    all_songs=subprocess.check_output(["find",musicdir],text=True).rstrip().split('\n')
    all_songs = [
    song
    for song in all_songs
    if not ( song.endswith((".txt", ".vtt")) or (song in songs_in_playlist) )
    ]
    all_songs="\n".join(all_songs).rstrip()
    ## select songs from find
    selected_songs=subprocess.check_output(menu+["-p","Select Songs"],text=True,input=all_songs).rstrip()
    if selected_songs :
        with open(selected_playlist,'a') as FILE :
            FILE.write(selected_songs)


# Create Playlist
elif (mode=="Create Playlist") :
    ## Remove txt and vtt files from find
    all_songs=subprocess.check_output(["find",musicdir],text=True).rstrip().split('\n')
    all_songs = [
    song
    for song in all_songs
    if not song.endswith((".txt", ".vtt"))
]
    all_songs="\n".join(all_songs).rstrip()
    ## select songs from find
    selected_songs=subprocess.check_output(menu+["-p","Select Songs"],text=True,input=all_songs).rstrip()
    

    ## Name Playlist
    playlist_name = subprocess.check_output(menu+["-p","Name the Playlist"],text=True,input="").rstrip()
    with open(musicdir+"Playlists/"+playlist_name+".txt",'w') as playlist_file :
        playlist_file.write(selected_songs)


# Play Playlist
elif (mode=="Play Playlist") :
    all_playlists=subprocess.check_output(["ls",musicdir+"Playlists/"],text=True).rstrip()
    selected_playlist=subprocess.check_output(menu+["-p","Select a playlist"],text=True,input=all_playlists).rstrip()
    selected_playlist=musicdir+"Playlists/"+selected_playlist
    print(selected_playlist)
    # Now run `find` in selected_playlist and store it to a temporary file. Mpv will play from this temporary file so that it can shuffle properly

    #shuffled_playlist = subprocess.check_output(f'cat "{selected_playlist}" | xargs -I [] find  "[]" -type f | shuf',shell=True,text=True).rstrip()
    with open(selected_playlist) as FILE :
        all_songs =  [ i.rstrip() for i in FILE.readlines() ]
    appendlist = []
    for i in range(len(all_songs)-1,-1,-1) :
        if os.path.isdir(all_songs[i]) :
            appendlist += list(subprocess.check_output(["find",all_songs[i],"-type","f"],text=True).split('\n'))
            del all_songs[i]
    all_songs += appendlist

    # Remove empty entries
    for i in range(len(all_songs)-1,-1,-1) :
        if not all_songs[i] :
            del all_songs[i]

    import random
    random.shuffle(all_songs)
    shuffled_playlist = "\n".join(all_songs)


    with tempfile.NamedTemporaryFile(mode='w+',delete=False,suffix=".txt") as tmp:
        
        tmp.write(shuffled_playlist)
        tmppath = tmp.name
    subprocess.run(['mpv','ao=alsa','--player-operation-mode=pseudo-gui','-fs','--sub-pos=55','--sub-scale=0.75','--no-resume-playback',"--playlist="+tmppath,'--shuffle=yes']+ARGS)
    os.unlink(tmppath)


elif (mode=="Play Song"):

    ## Remove txt and vtt files from find
    all_songs=subprocess.check_output(["find",musicdir],text=True).rstrip().split('\n')
    for song in all_songs:
        if song[-3:] in ["vtt","txt"] :
            all_songs.remove(song)
    all_songs="\n".join(all_songs).rstrip()
    ## select songs from find
    selected_songs=subprocess.check_output(menu +["-p","Select Songs"],text=True,input=all_songs).rstrip()
    selected_songs = selected_songs.split('\n')
    subprocess.run(['mpv','ao=alsa','--player-operation-mode=pseudo-gui','-fs','--sub-pos=55','--sub-scale=0.75','--no-resume-playback']+selected_songs+['--shuffle=yes']+ARGS)

