#!/bin/sh
menu="$(for j in $@; do echo $j; done | grep '^-m=' | awk -F '=' '{print $2}')"
[ "$menu" ] || menu="dmenu -i -l 30"
if [ ! $FILENAME ]
then
FILENAME="$(find $HOME ! -type d  | $menu)"
#FILENAME="$(fzf --preview="timg {} -g100x100 || batcat {} --color=always")"
fi
if [ "$FILENAME" ]
then
FILEEXTENTION="$(echo "$FILENAME" | awk -F '.' '{print $NF}')"
DOCUMENT_VIEWER="zathura"
MEDIA_PLAYER="mpv"
IMAGE_VIEWER="sxiv"
if [ "$menu" = "dmenu -l 30" ]
then
TEXT_EDITOR="st -e vi"
else
TEXT_EDITOR="vi"
fi
GOOD_APP=""
case $FILEEXTENTION in
	pdf | djvu | ps | epub )
		GOOD_APP="$DOCUMENT_VIEWER";;
	png | jpg | webp )
		GOOD_APP="$IMAGE_VIEWER" ;;
	mp4 | m4a | m3u | webm | mp3 | opus | mkv | wav )
		GOOD_APP="$MEDIA_PLAYER" ;;
	*)
		GOOD_APP="$TEXT_EDITOR" ;;
esac
OPTS=""
[ "$GOOD_APP" = "$DOCUMENT_VIEWER" ] && OPTS="--mode fullscreen"
[ $FILEEXTENTION ] && $GOOD_APP "$FILENAME" $OPTS
fi
