#!/bin/bash
theme=""
alpha=""
backend=""
col_mode=""
wal_enable="1"
declare args=("$@")
for arg in "${args[@]}"	
do
	if [ -f "$arg" ]
	then
		theme="$arg"
	else
		case "$arg" in
			-a=* )
				alpha="${arg#*=}" ;;
			-l )
				col_mode="-l" && backend="--backend colorz" ;;
			-w )
				wal_enable="" ;;
		esac
	fi
	
done
[ "$alpha" ] && alpha="-a $alpha"
if [ "$theme" ]
then
wal -s -n $backend $col_mode -i "$theme" 
walscript $alpha $col_mode
[ "$wal_enable" ] && sudo cp "$theme" /usr/share/wallpapers/wal && setbg "$theme"
cd $WM_SETUP_DIR/dmenu
sudo make clean install
cd $WM_SETUP_DIR/dwm
sudo make clean install
cd $WM_SETUP_DIR/st
sudo make clean install
cd $HOME
kill -HUP $(pidof dwm)
fi
