#!/bin/python3
import sys, os , subprocess
DIRS = []
ARGS = []
if len(sys.argv) > 1 : 
    for i in sys.argv[1:] :
        if os.path.isdir(os.path.realpath(i)) :
            DIRS.append(os.path.realpath(i))
        else :
            ARGS.append(i)

ARGS += ['--shuffle=yes']

if not(DIRS) :
    MusicDIRS = subprocess.check_output(['find',os.path.expanduser("~/Music/"),'-type','d'],text=True).rstrip().split('\n')
    for i in range(len(MusicDIRS)) :
        MusicDIRS[i] = os.path.relpath(MusicDIRS[i],os.path.expanduser("~/Music/"))
    MusicDIRS="\n".join(MusicDIRS)
    selDIRS = subprocess.check_output(['dmenu','-i','-l','30'],input=MusicDIRS,text=True).rstrip()
    for dir in selDIRS.split('\n') :
        DIRS.append(os.path.join(os.path.expanduser("~/Music/"),dir))


if "--ind-dirs" in sys.argv :   
    for dir in DIRS : 
        FILES = []
        if "image" in os.listdir(dir):
            WAL = os.path.join(dir,"image")
        else :
            WAL = "/usr/share/wallpapers/wal"
        for i in os.listdir(dir) :
            if i != "image" and ( ".vtt" not in i) and ( ".srt" not in i ) :
                FILES.append(os.path.join(dir,i))
        subprocess.run(['mpv','--no-video','','--player-operation-mode=pseudo-gui','-fs','--sub-pos=55','--sub-scale=0.75','--no-resume-playback','--cover-art-file='+WAL,'--vid=1']+FILES+ARGS)
else :
    FILES = []
    for dir in DIRS : 
        for i in list(subprocess.check_output(['find',dir,'-type','f'],text=True).split('\n')) :
            for j in ['mp4','mp3','opus','mkv','webm','m4a'] :
                if j in i and not(os.path.join(dir,i) in FILES):
                    FILES.append(os.path.join(dir,i))
    subprocess.run(['mpv','--no-video','','--player-operation-mode=pseudo-gui','-fs','--sub-pos=55','--sub-scale=0.75','--no-resume-playback','--vid=1','--af=lavfi=[loudnorm=I=-16:TP=-3:LRA=4]']+FILES+ARGS)
