#!/bin/sh
VM="$(ls $HOME/Qemu/VMs/*.vm | ( dmenu -l 5 || fzf) )"
efi_enab="$(echo "$VM" | grep ".uefi.")"
extra_storage="$HOME/Qemu/common_drives/vm_storage"
use_storage=""

for i in $@
do
	case $i in 
	-n )
	net="1" ;;
	-s )
	use_storage=1 ;;
	esac
done

if [ "$VM" ]
then
if [ $use_storage ]
then
	[ -f "$extra_storage" ]	&& extra_storage="-hdb $extra_storage"
fi
[ "$net" ] && net="-nic user,hostfwd=tcp::60022-:22"

if [ $efi_enab ]
then
qemu-system-x86_64  $VM -device virtio-vga-gl gtk,gl=on ${use_storage} -m 4G -enable-kvm -smp 8 -cpu host -device AC97 $net -m -bios /usr/share/ovmf/OVMF.fd
else
qemu-system-x86_64  $VM -device virtio-vga-gl -display gtk,gl=on,full-screen=on -m 4G -enable-kvm -smp 8 -cpu host  -device AC97 $net
fi
fi
