#!/bin/bash
searchquery=""
FORMAT=""
dmode=""
# Handling dmode and FORMAT
for i in "$@"
do
	FORMAT+="$(echo "$i" | grep "^-F=" | awk -F "=" '{print $2}')"
done

for i in "$@"
do
	dmode+="$(echo "$i" | grep "^-d$")"
done


for i in "$@"
do
	if [ "$(echo "$i" | grep -v "^-" )"  ]
	then
		searchquery="$searchquery $i"
	fi
done

if [ -z "$searchquery" ]
then
searchquery="$(:|dmenu -p "Searchquery" )"
fi
curl "https://invidious.snopyta.org/search?q=$(echo "$searchquery" | sed 's/\ /+/g')&type=video" > /tmp/searchquery
curl "https://invidious.snopyta.org/search?q=$(echo "$searchquery" | sed 's/\ /+/g')&type=video&page=2" >> /tmp/searchquery
curl "https://invidious.snopyta.org/search?q=$(echo "$searchquery" | sed 's/\ /+/g')&type=video&page=3" >> /tmp/searchquery
grep "p dir=\"auto\"" /tmp/searchquery | grep -v "&nbsp" | awk -F ">" '{print $3}' | sed 's/<\/p//g' | sed 's/\ /_/g' > /tmp/searchtitle
grep channel-name /tmp/searchquery |   awk -F ">" '{print $2}' | awk -F "&nbsp" '{print $1}' | sed 's/<\/p//g' | sed 's/\ /_/g' > /tmp/channelname
grep youtube /tmp/searchquery | grep watch | awk -F "\"" '{print $4}'  > /tmp/searchurl
URLLINK="$(paste /tmp/searchtitle /tmp/channelname /tmp/searchurl | column -t | uniq |  dmenu -l 30 | awk '{print $NF}')"
if [ $dmode ]
then
	[ $FORMAT ] && FORMAT="--format=$FORMAT"
   	yt-dlp $FORMAT -o "$HOME/Videos/yt-dlp/%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" "$URLLINK" 
else
	[ $FORMAT ] && FORMAT="--ytdl-format=$FORMAT"
	mpv "$URLLINK" $FORMAT
fi
